##' ## Total Trade CPC
##'
##' **Author: Alex Matrunich, Marco Garieri, Bo Werth, Christian Mongeau**
##'
##' **Description:**
##'
##' The trade module is divided in two submodules: **complete\_tf\_cpc** and
##' **total\_trade\_CPC**. Each module is year specific. This means that, at the
##' time being, the trade module run indipendently for each year. In order to
##' run the **tt total\_trade\_CPC**, the output of **complete\_tf\_cpc** is
##' needed.
##'
##' This module aggregates total trade flow by reporting country for partners
##' countries to a single total trade for each unique CPC commodity code. The
##' module save the ouput into the dataset **total\_trade\_cpc\_m49**,
##' within the **Trade** domain.
##'
##' Change Log:
##'
##' - add unit values to output


##+ setup, echo=FALSE, eval=FALSE

# Year for processing
library(faoswsTrade)
library(faosws)
library(stringr)
library(scales)
library(faoswsUtil)
library(faoswsFlag)
library(tidyr)
library(dplyr, warn.conflicts = F)

local({
  min_versions <- data.frame(package = c("faoswsFlag", "faoswsTrade"),
                             version = c('0.2.4', '0.1.1'),
                             stringsAsFactors = FALSE)

  for (i in nrow(min_versions)){
    # installed version
    p <- packageVersion(min_versions[i,"package"])
    # required version
    v <- package_version(min_versions[i,"version"])
    if(p < v){

      stop(sprintf("%s >= %s required", min_versions[i,"package"], v))
    }
  }

})


if(CheckDebug()){
  library(faoswsModules)
  SETTINGS = ReadSettings("modules/total_trade_CPC/sws.yml")
  ## Define where your certificates are stored
  faosws::SetClientFiles(SETTINGS[["certdir"]])
  ## Get session information from SWS. Token must be obtained from web interface
  GetTestEnvironment(baseUrl = SETTINGS[["server"]],
                     token = SETTINGS[["token"]])
}

year <- as.integer(swsContext.computationParams$year)

startTime = Sys.time()

##' ### Import Data from Complete TF CPC
##'
##' Import monetary values and quantities from data previously generated by
##' **complete_tf_cpc** module.
##' 
##' 1. `5608`: Import Quantity (heads)
##' 2. `5609`: Import Quantity (1000 heads)
##' 3. `5610`: Import Quantity (tonne)
##' 4. `5908`: Export Quantity (heads)
##' 5. `5909`: Export Quantity (1000 heads)
##' 6. `5910`: Export Quantity (tonne)
##' 7. `5622`: Imports (US$)
##' 8. `5922`: Exports (US$)

##+ import, echo=FALSE, eval=FALSE

allReporterKeys <- GetCodeList("trade", "completed_tf_cpc_m49", "geographicAreaM49Reporter")[type == "country", code]
allPartnerKeys <- GetCodeList("trade", "completed_tf_cpc_m49", "geographicAreaM49Partner")[type == "country", code]
allElementKeys <- c("5608", "5609", "5610", "5908", "5909", "5910",
                    "5622", "5922") # monetary values to calculate unit values
allItemKeys <- GetCodeList("trade", "completed_tf_cpc_m49", "measuredItemCPC")[,code]

completetradekey <- DatasetKey(domain = "trade", dataset = "completed_tf_cpc_m49",
                               dimensions = list(
                                 geographicAreaM49Reporter = Dimension(name = "geographicAreaM49Reporter", keys = allReporterKeys),
                                 geographicAreaM49Partner = Dimension(name = "geographicAreaM49Partner", keys = allPartnerKeys),
                                 measuredElementTrade = Dimension(name = "measuredElementTrade", keys = allElementKeys),
                                 measuredItemCPC = Dimension(name = "measuredItemCPC", keys = allItemKeys),
                                 timePointYears = Dimension(name = "timePointYears", keys = as.character(year))
                               ))

completetrade <- tbl_df(GetData(completetradekey))

completetrade <- completetrade %>%
  mutate_(geographicAreaM49 = ~geographicAreaM49Reporter)

total_trade_cpc_wo_uv <- completetrade %>%
  select_(~geographicAreaM49, ~geographicAreaM49Partner, ~timePointYears,
          ~measuredItemCPC, ~measuredElementTrade, ~Value, ~flagObservationStatus) %>%
  group_by_(~geographicAreaM49, ~timePointYears, ~measuredItemCPC, ~measuredElementTrade) %>%
  summarise_(Value = ~sum(Value, na.rm = TRUE),
             flagObservationStatus = ~aggregateObservationFlag(flagObservationStatus)) %>%
  ungroup()


##' ### Calculate Unit Values
##'
##' Calculate unit value (US$ per quantity unit) at CPC level if the quantity is
##' larger than zero
##'
##' 1. `5630`: Import Unit Value (US$ / tonne)
##' 2. `5638`: Import Unit Value (US$ / heads)
##' 3. `5639`: Import Unit Value (US$ / 1000 heads)
##' 4. `5930`: Export Unit Value (US$ / tonne)
##' 5. `5938`: Export Unit Value (US$ / heads)
##' 6. `5939`: Export Unit Value (US$ / 1000 heads)

##+ unit-value, echo=FALSE, eval=FALSE

addUV <- function(data) {

  ## data <- total_trade_cpc
  copyData <- data
  
  copyData$unit <- ifelse(copyData$measuredElementTrade %in% c("5622", "5922"), "monetary", "quantity")
  copyData$flow <- ifelse(substr(copyData$measuredElementTrade, 1, 2) == "56", "import", "export")

  copyData_quantity <-
    copyData %>%
    filter(unit == "quantity") %>%
    select(-unit, measuredElementTrade.qty = measuredElementTrade)
    ## select(-unit) # must keep to assign proper elemnt code to unit value

  copyData_monetary <-
    copyData %>%
    filter(unit == "monetary") %>%
    select(-unit, -measuredElementTrade, -flagObservationStatus)

  me_qty_uv <- data.frame(flow = c(rep("import", 3), rep("export", 3)),
                          measuredElementTrade.qty = c("5608", "5609", "5610", "5908", "5909", "5910"),
                          measuredElementTrade = c("5638", "5639", "5630", "5938", "5939", "5930"),
                          stringsAsFactors = FALSE)

  copyData_uv <-
    copyData_quantity %>%
    left_join(copyData_monetary,
              by = c("geographicAreaM49", "timePointYears", "measuredItemCPC","flow"),
              suffix = c(".qty", ".mon")) %>%
    mutate(Value = ifelse(Value.qty > 0, Value.mon * 1000 / Value.qty, NA)
           ) %>%
    left_join(me_qty_uv) %>%
    ## ## only keep columns already present in input data set
      subset(., select = names(data))
  
  return(copyData_uv)
  
}

total_trade_cpc_uv <- addUV(total_trade_cpc)

total_trade_cpc_w_uv <- 
  total_trade_cpc_wo_uv %>%
  bind_rows(total_trade_cpc_uv)


total_trade_cpc$flagMethod = "s"

stats <- SaveData("trade","total_trade_cpc_m49",data.table::as.data.table(total_trade_cpc))

sprintf(
  "Module completed in %1.2f minutes.
  Values inserted: %s
  appended: %s
  ignored: %s
  discarded: %s",
  difftime(Sys.time(), startTime, units = "min"),
  stats[["inserted"]],
  stats[["appended"]],
  stats[["ignored"]],
  stats[["discarded"]]
)

### TO DO FCL
#total_trade_fcl <- total_trade %>%
#  transmute_(geographicAreaM49 = ~reporterM49,
#             measuredElementTrade = ~ifelse(flow == 1,
#                                            "5610",
#                                            ifelse(flow == 2,
#                                                   "5910",
#                                                   NA)),
#             measuredItemFS = ~fcl,
#             timePointYears = ~year,
#             flagObservationStatus = ~flagObservationStatus,
#             flagMethod = ~flagMethod,
#             qty = ~qty,
#             fclunit = ~fclunit,
#             value = ~value)
